title: L'aventure palpitante d'un castor et d'un pivert !

github:
  is_project_page: false
  show_downloads: False


remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


logo: images/chloe.jpg


